//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoCenter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfoCenter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _0_star_rating {
            get {
                object obj = ResourceManager.GetObject("_0_star_rating", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1_star_rating {
            get {
                object obj = ResourceManager.GetObject("_1_star_rating", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2_star_rating {
            get {
                object obj = ResourceManager.GetObject("_2_star_rating", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _3_star_rating {
            get {
                object obj = ResourceManager.GetObject("_3_star_rating", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addCodSursa32 {
            get {
                object obj = ResourceManager.GetObject("addCodSursa32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap codesnippet32 {
            get {
                object obj = ResourceManager.GetObject("codesnippet32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon iconInfoCenter {
            get {
                object obj = ResourceManager.GetObject("iconInfoCenter", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgAdd16 {
            get {
                object obj = ResourceManager.GetObject("imgAdd16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgAlert16 {
            get {
                object obj = ResourceManager.GetObject("imgAlert16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgAlert32 {
            get {
                object obj = ResourceManager.GetObject("imgAlert32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgBackground {
            get {
                object obj = ResourceManager.GetObject("imgBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgBacup {
            get {
                object obj = ResourceManager.GetObject("imgBacup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgBold16 {
            get {
                object obj = ResourceManager.GetObject("imgBold16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgClock32 {
            get {
                object obj = ResourceManager.GetObject("imgClock32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgClose32 {
            get {
                object obj = ResourceManager.GetObject("imgClose32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgCompile16 {
            get {
                object obj = ResourceManager.GetObject("imgCompile16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgCompile36 {
            get {
                object obj = ResourceManager.GetObject("imgCompile36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgCompile361 {
            get {
                object obj = ResourceManager.GetObject("imgCompile361", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgCompileBig36 {
            get {
                object obj = ResourceManager.GetObject("imgCompileBig36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgDecreaseFont16 {
            get {
                object obj = ResourceManager.GetObject("imgDecreaseFont16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgDetalii16 {
            get {
                object obj = ResourceManager.GetObject("imgDetalii16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgError16 {
            get {
                object obj = ResourceManager.GetObject("imgError16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgError32 {
            get {
                object obj = ResourceManager.GetObject("imgError32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgIncreaseFont16 {
            get {
                object obj = ResourceManager.GetObject("imgIncreaseFont16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgItalic16 {
            get {
                object obj = ResourceManager.GetObject("imgItalic16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgLoading {
            get {
                object obj = ResourceManager.GetObject("imgLoading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgLogoHorizontal {
            get {
                object obj = ResourceManager.GetObject("imgLogoHorizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgLogoVertical {
            get {
                object obj = ResourceManager.GetObject("imgLogoVertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgMareste16 {
            get {
                object obj = ResourceManager.GetObject("imgMareste16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgOk16 {
            get {
                object obj = ResourceManager.GetObject("imgOk16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgOk32 {
            get {
                object obj = ResourceManager.GetObject("imgOk32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgOptiuni {
            get {
                object obj = ResourceManager.GetObject("imgOptiuni", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgPlay16 {
            get {
                object obj = ResourceManager.GetObject("imgPlay16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgPlay32 {
            get {
                object obj = ResourceManager.GetObject("imgPlay32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgPrint32 {
            get {
                object obj = ResourceManager.GetObject("imgPrint32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgProbleme32 {
            get {
                object obj = ResourceManager.GetObject("imgProbleme32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgPunctaj32 {
            get {
                object obj = ResourceManager.GetObject("imgPunctaj32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgRefresh32 {
            get {
                object obj = ResourceManager.GetObject("imgRefresh32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgRun {
            get {
                object obj = ResourceManager.GetObject("imgRun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgRun1 {
            get {
                object obj = ResourceManager.GetObject("imgRun1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSave16 {
            get {
                object obj = ResourceManager.GetObject("imgSave16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSave32 {
            get {
                object obj = ResourceManager.GetObject("imgSave32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSave32_2 {
            get {
                object obj = ResourceManager.GetObject("imgSave32_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSaveAs32 {
            get {
                object obj = ResourceManager.GetObject("imgSaveAs32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSaveAs32_2 {
            get {
                object obj = ResourceManager.GetObject("imgSaveAs32_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSetariImprimanta {
            get {
                object obj = ResourceManager.GetObject("imgSetariImprimanta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgTest32 {
            get {
                object obj = ResourceManager.GetObject("imgTest32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgTestare {
            get {
                object obj = ResourceManager.GetObject("imgTestare", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgToate16 {
            get {
                object obj = ResourceManager.GetObject("imgToate16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgWrong16 {
            get {
                object obj = ResourceManager.GetObject("imgWrong16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgZoom32 {
            get {
                object obj = ResourceManager.GetObject("imgZoom32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logoc {
            get {
                object obj = ResourceManager.GetObject("logoc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logoRibbon {
            get {
                object obj = ResourceManager.GetObject("logoRibbon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
